---
######################## Start of Code ########################
# Configure physical interfaces on all routers within topology

- name: Configure IPs on interconnect interfaces
  hosts: routers
  gather_facts: no
  vars_files:
    - interface_vars.yml

  tasks:
    - name: Configure interface IPs
      cisco.ios.ios_config:
        lines:
          - ip address {{ item.ip }} {{ item.mask }}
          - no shutdown
        parents: "interface {{ item.name }}"
      loop: "{{ interfaces[inventory_hostname] }}"

######################## End of Code ########################         