---
datacentre:
  children:
    routers:
      hosts:
        C8KV-1:
          ansible_host: 100.71.34.101
        C8KV-2:
          ansible_host: 100.71.34.102
        C8KV-3:
          ansible_host: 100.71.34.103
        C8KV-4:
          ansible_host: 100.71.34.104
      vars:
        testVar: 999
#    switches:
#      hosts:
#        100.71.34.10[5:9]:
  vars:
    ansible_network_os: ios
    ansible_user: admin
    ansible_password: Admin12345
    ansible_become_password: Admin12345
    ansible_connection: network_cli
#    ntp_servers:
#      - 8.8.8.8
#      - 8.8.4.4